[package]
name = "desmosify"
version = "0.1.0"
edition = "2024"
authors = ["xarkenz"]
description = "A compiler that outputs Desmos graphs"

[features]
default = []
clap = ["dep:clap"]

[dependencies]
clap = { version = "4.6", features = ["derive"], optional = true }
dataurl = "0.1"
json = "0.12"
mime_guess = "2.0"
