title: Desmosify
description: The official documentation for the Desmosify language

theme: just-the-docs

aux_links_new_tab: true
aux_links:
    GitHub Repository: https://github.com/xarkenz/desmosify

callouts:
    note:
        title: Note
        color: blue
    compatibility-note:
        title: Compatibility Note
        color: yellow
    warning:
        title: Warning
        color: red
    error:
        color: red

url: https://xarkenz.github.io/desmosify
desmos_url: https://www.desmos.com
toc_header: Table of Contents
# This key has to be used in order to embed Desmos
desmos_api_key: cbcc1b6daaef4b1cbd8a8d86a720847a
